### ISSUE TITLE
No placeholders present on page

### ISSUE THREAD

**Issue by JonnyVickers** [Cognifide/Sitecore.XA.Showcase#1]
Hi There,

I've been attempting to get your showcase project up and running for a few hours now.  The Showcase site appears to be installed correctly - however experience editor isn't able to see any placeholders on the page.

I tried an older version of the project from April 23rd and it works as expected (7b58d0a44376768d1bbbabe98e022913955e6dcd)

I've also noticed that in the current version the ComponentType field is missing from the serialisation folder under the Component Template.

Thanks,
Jonathan

**Comment by devzbysiu** [comment]
Closing. This project is no longer maintained.
